# Generated by Django 4.2.7 on 2025-11-15 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avg_transaction_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="customer_rating",
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_regular_income",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="high_risk_transactions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="income_consistency_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="max_transaction_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="min_transaction_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mpesa_activity_level",
            field=models.CharField(default="low", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mpesa_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mpesa_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="negative_balance_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="overdraft_frequency",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="primary_transaction_times",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="transaction_count_30d",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="transaction_count_90d",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=50, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("send_money", "Send Money"),
                            ("pay_bill", "Pay Bill"),
                            ("buy_goods", "Buy Goods"),
                            ("receive_money", "Receive Money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "balance_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("sender", models.CharField(blank=True, max_length=15)),
                ("receiver", models.CharField(blank=True, max_length=15)),
                ("description", models.TextField(blank=True)),
                ("transaction_time", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("is_high_risk", models.BooleanField(default=False)),
                ("risk_reason", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mpesa_transactions",
                "indexes": [
                    models.Index(
                        fields=["user", "transaction_time"],
                        name="mpesa_trans_user_id_d32a49_idx",
                    ),
                    models.Index(
                        fields=["transaction_time"],
                        name="mpesa_trans_transac_267552_idx",
                    ),
                ],
            },
        ),
    ]
